version: "3.9"

services:
  app:
    container_name: "backend-api"
    build: .
    command: bash -c "alembic upgrade head && uvicorn app.main:app --factory --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always
    networks:
      - "backend-network"

  db:
    container_name: "backend-db"
    image: postgres:16-bookworm
    restart: always
    volumes:
      - backend_postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - .env
    networks:
      - "backend-network"

  docs:
    container_name: "backend-docs"
    image: squidfunk/mkdocs-material:latest
    restart: always
    volumes:
      - .:/docs
    ports:
      - "8001:8000"
    networks:
      - "backend-network"

  pgadmin:
    container_name: "backend-pgadmin"
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - db
    restart: always
    env_file:
      - .env
    networks:
      - "backend-network"

volumes:
  backend_postgres_data: {}

networks:
  backend-network:
    driver: bridge
