site_name: python-backend-template
repo_name: python-backend-template
repo_url: https://github.com/goldginkgo/python-backend-template
copyright: Copyright &copy; 2023 Frank Dai
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: teal
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.sections
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - navigation.footer

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/goldginkgo/python-backend-template

nav:
  - Overview: index.md
  - Development:
      # - development/index.md
      # - ./LICENSE
      - development/usage.md
